### ISSUE TITLE
Request standalone

### ISSUE THREAD

**Issue by ravingdragoon** [MarkPearce/footsteps-of-otari#1]
Sorry to leave this as an "issue" but there isn't a good way to start a conversation on Github.  Would it be possible for you to release a standalone version of this? It is really cool, and would be awesome for any haunted environment.

**Comment by MarkPearce** [comment]
No worries, a feature request is also an issue of sorts.

I been giving that some thought… the challenge is how to best control the
ghost. Right now it follows predefined .SVG paths.

I could imagine adding an ‘import path’ feature but then people would have
to be comfortable with making their own SVGs.  Lots of ways that could
break:  data format, size, orientation and placement.

Another alternative may be to add a ‘follow cursor’ mode.  When the GM
could click the map to spawn a ghost, and it would follow their mouse until
they click again….

The problem is then you need to control the the ghost. Not do everything
else the GM should be doing.

I’ll think on it some more. Maybe I could come up with some kind of record
mode, or just get the path from a Foundry shape layer, that’s probably the
best way to do it.

I’m working on some more maps for the module though, finish up the artwork
1st.  But I like the idea of making a stand-alone ghosty.

**Comment by CottonCthulhu** [comment]
Thanks for writing the module and the explanation, that helped alot. I try to piggyback your script to use in my own map and I'd run into the problem, that I don't know how to map the .SVG path correctly onto the scene. I found the paths in your code, but I can't figure out how to draw a new path that isn't horribly mangled. Could you give me a few pointers?
Thank you very much!

**Comment by MarkPearce** [comment]
Yea, it would be really hard to do inside foundry.  What I did to create the path information is is import the level  images into adobe illustrator, draw the path using the spline tool, then export that layer as an SVG.

then copy that svg code into the JavaScript,

that’s why it reallly only works as pre-generated routes, you need that path as a variable. (For the greensock animation) 

To have something dynamic you need write a whole new system to control the sprite position…. Or a way to create svgs in foundry

**Comment by MarkPearce** [comment]
If I remember correctly the svg needs a bounding box which matches the map image size,

**Comment by CottonCthulhu** [comment]
That was it, I ruined the image size and therefore the bounding box in my first try. Thank you very much, again!
